export {
  openAppById,
  focusOrOpenAppById,
  closeWindowById,
  minimizeWindowById,
  terminateProcessById,
  focusWindowById,
  restoreWindowById,
  maximizeWindowById,
  openNotesWithPrefill,
  openEditorWithFile,
  openAgentWithRequest,
  openBlogWithFocus,
  openClockWithFocus,
  openNotesWithRequest,
  openResumeWithFocus,
  openPortfolioWithFocus,
  openSystemInfoWithRequest,
  openTerminalWithRequest,
  openTerminalWithCommand,
  getRuntimeSnapshot,
} from "./os-actions";
