export {
  FILE_SYSTEM_CHANGE_EVENT,
  dispatchFileSystemChange,
  subscribeToFileSystemChanges,
  isFileSystemChangeForPath,
  isFileSystemChangeWithinPath,
  type FileSystemChangeDetail,
  type FileSystemChangeType,
} from "./fs-events";
export {
  NOTES_FILE_EXTENSION,
  PERSISTED_FILE_PATHS,
  LEGACY_FILE_PATHS,
  SYSTEM_ROOT,
  SYSTEM_APPS_ROOT,
  SYSTEM_USER_ROOT,
  SYSTEM_SHARED_ROOT,
  SYSTEM_CACHE_ROOT,
  SYSTEM_APP_DIRECTORIES,
  SYSTEM_USER_DIRECTORIES,
  SYSTEM_SHARED_DIRECTORIES,
  SYSTEM_CACHE_DIRECTORIES,
} from "./fs-paths";
export {
  existsAtPath,
  getNodeAtPath,
  listPath,
  readFileAtPath,
  readJsonAtPath,
  writeFileAtPath,
  writeFileAtPathOrCreate,
  writeJsonAtPath,
  createFileAtPath,
  createDirectoryAtPath,
  ensureDirectoryAtPath,
  deleteAtPath,
  moveToPath,
  copyToPath,
} from "./fs-actions";
export { readFsJsonAtPath } from "./fs-file-storage";
export { runDataMigration, type MigrationResult } from "./fs-migration";
export {
  computeChecksum,
  getAllNodes,
  getNode,
  getNodesByParent,
  putNode,
  putNodeAndContent,
  putNodes,
  deleteNode,
  deleteNodes,
  getContent,
  putContent,
  putContents,
  putNodeContentAndMeta,
  readJsonFile,
  writeJsonFile,
  deleteContent,
  deleteContents,
  getAllContents,
  getMeta,
  getAllMeta,
  setMeta,
  isSeeded,
  seedDefaultFileSystem,
  exportAll,
  clearAll,
  DEFAULT_DIR_IDS,
} from "./idb-storage";
